"""
OTRAS OPCIONES:
F1 : LISTA DE OPCIONES EN VSCODE

LISTA DE OPCIONES EN VSCODE:
'select interpreter' : establecer la terminal con el entorno virtual

TERMINAL:
'cls' : LIMPIAR CONSOLA

VIRTUALENV:
'pip install virtualenv'
'virtualenv 'nombre_entorno_virtual'' : CREAR ENTORNO (ESTO CREA UNA CARPETA)
".\entorno_virtual\Scripts\activate" : 'ACTIVAR ENTORNO

DJANGO:
'django-admin startproject nombre_proyecto_django .' : CREAR PROYECTO DJANGO ( ' .' AL FINAL HACE QUE NO CREE DOBLE CARPETA)
'__pycache__' : la carpeta guarda código que ya compilo python para que se ejecute mas rápido

solo un ejemplo para ver si es add

"""