# archivo creado al hacer migraciones de datos de modelos de la app a la base de datos
# Generated by Django 4.1.7 on 2023-04-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clase_proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clase_proyectos', models.CharField(max_length=200)),
            ],
        ),
    ]
