# Generated by Django 4.1.7 on 2023-04-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpeta_aplicacion_1', '0002_clase_tareas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clase_tareas',
            old_name='descripcion_clase_tareas',
            new_name='descripcion_clase_tareasx',
        ),
        migrations.AddField(
            model_name='clase_tareas',
            name='enproceso_terminado',
            field=models.BooleanField(default=False),
        ),
    ]
