# Generated by Django 4.1.7 on 2023-04-06 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpeta_aplicacion_1', '0003_rename_descripcion_clase_tareas_clase_tareas_descripcion_clase_tareasx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clase_proyectos',
            old_name='nombre_clase_proyectos',
            new_name='nombre_modelo_proyectos',
        ),
    ]
