# Generated by Django 4.1.7 on 2023-04-06 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpeta_aplicacion_1', '0004_rename_nombre_clase_proyectos_clase_proyectos_nombre_modelo_proyectos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clase_proyectos',
            new_name='modelo_proyectos',
        ),
    ]
