# Generated by Django 4.1.7 on 2023-04-06 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpeta_aplicacion_1', '0007_rename_clase_tareas_tabla_tareas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabla_proyectos',
            old_name='nombre_modelo_proyectos',
            new_name='tab_proyectos_col_nombres',
        ),
    ]
