# Generated by Django 4.1.7 on 2023-04-06 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpeta_aplicacion_1', '0008_rename_tabla_proyectos_col_nombres_tabla_proyectos_tab_proyectos_col_nombres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabla_tareas',
            old_name='descripcion_clase_tareasx',
            new_name='tab_tareas_col_descripcion',
        ),
        migrations.RenameField(
            model_name='tabla_tareas',
            old_name='titulo_clase_tareas',
            new_name='tab_tareas_col_nombre',
        ),
        migrations.RenameField(
            model_name='tabla_tareas',
            old_name='n_proyecto_clase_tareas',
            new_name='tab_tareas_col_proyecto_ref',
        ),
        migrations.RenameField(
            model_name='tabla_tareas',
            old_name='enproceso_terminado',
            new_name='tab_tareas_col_terminado',
        ),
    ]
