# Generated by Django 4.1.7 on 2023-04-07 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpeta_aplicacion_1', '0009_rename_descripcion_clase_tareasx_tabla_tareas_tab_tareas_col_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabla_proyectos',
            old_name='tab_proyectos_col_nombres',
            new_name='nombre_clase_proyectos',
        ),
    ]
