# Generated by Django 4.1.7 on 2023-04-07 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpeta_aplicacion_1', '0010_rename_tab_proyectos_col_nombres_tabla_proyectos_nombre_clase_proyectos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabla_proyectos',
            old_name='nombre_clase_proyectos',
            new_name='tab_proyectos_col_nombres',
        ),
    ]
